name: Build for Windows ARM64

on:
  push:

jobs:
  build-windows-arm64:
    name: Build
    runs-on: ubuntu-latest
    env:
      aria2_version: "1.37.0"
      libssh2_version: "1.11.0"
      llvm_path: "${{ github.workspace }}/llvm-mingw"
      libssh2_path: "${{ github.workspace }}/libssh2-windows-arm64"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install \
            build-essential cmake ninja-build pkg-config p7zip
          wget https://github.com/mstorsjo/llvm-mingw/releases/download/20220906/llvm-mingw-20220906-ucrt-ubuntu-18.04-x86_64.tar.xz
          tar -xf llvm-mingw-*.tar.xz
          mv llvm-mingw-20220906-ucrt-ubuntu-18.04-x86_64 llvm-mingw
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          
      - name: Install libraries from vcpkg
        run: |
          PATH=$PATH:${{ env.llvm_path }}/bin
          cd vcpkg
          git apply ${{ github.workspace }}/patches/vcpkg-disable-asm-for-arm32.patch
          # tell vcpkg to only build Release variants of the dependencies
          mkdir triplets_overlay
          cp triplets/community/arm64-mingw-static.cmake triplets_overlay/arm64-mingw-static-release.cmake
          cp triplets/community/arm-mingw-static.cmake triplets_overlay/arm-mingw-static-release.cmake
          echo "set(VCPKG_BUILD_TYPE release)" >> triplets_overlay/arm64-mingw-static-release.cmake
          echo "set(VCPKG_BUILD_TYPE release)" >> triplets_overlay/arm-mingw-static-release.cmake
          # clear buildtrees after each package installation to reduce disk space requirements
          packages="zlib expat sqlite3 c-ares gmp"
          ./vcpkg upgrade \
            --overlay-triplets=triplets_overlay \
            --no-dry-run
          ./vcpkg install \
            --overlay-triplets=triplets_overlay \
            --clean-after-build \
            --triplet=arm64-mingw-static-release \
            $packages
          ./vcpkg install \
            --overlay-triplets=triplets_overlay \
            --clean-after-build \
            --triplet=arm-mingw-static-release \
            $packages

      - name: Build aria2
        run: |
          chmod 755 build.sh
          ./build.sh arm64
          ./build.sh arm32

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: aria2_woa
          path: aria2*.zip

      - name: Batch release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            aria2*.zip
    
